#Variables
@baseUrl = http://localhost:3000

#Health check
# @name healthCheck
GET {{baseUrl}}/health

###

#Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de Teste",
    "description": "Uma descrição para a Sala de Teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

#Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions
###

#Create questions
# @name createQuestion
POST {{baseUrl}}/rooms/6f05315b-1442-4bfa-af46-cf39d951f59e/questions
Content-Type: application/json

{
    "question": "o que é react?"
}
