version: latest
services:
    nlw-agents-pg:
        image: pgvector/pgvector:pg17
        environment:
            POSTGRES_HOST: database
            POSTGRES_PORT: 5432
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: agents
        ports:
            - "5432:5432"
        volumes:
            - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql # Initialize the database with the schema
